-- =============================================
-- Flowable数据库版本修复脚本
-- 用于解决 "unknown version from database" 错误
-- =============================================

-- 如果遇到版本冲突问题，可以执行以下操作：

-- 方案1: 删除所有Flowable表（会清空所有工作流数据，谨慎使用！）
-- 删除后，应用启动时会自动重新创建表

-- 查看所有Flowable表
-- SELECT TABLE_NAME FROM information_schema.TABLES 
-- WHERE TABLE_SCHEMA = DATABASE() 
-- AND TABLE_NAME LIKE 'ACT_%' OR TABLE_NAME LIKE 'FLW_%';

-- 删除所有Flowable相关表（取消注释下面的SQL来执行）
/*
DROP TABLE IF EXISTS ACT_ADM_DATABASECHANGELOG;
DROP TABLE IF EXISTS ACT_ADM_DATABASECHANGELOGLOCK;
DROP TABLE IF EXISTS ACT_APP_DATABASECHANGELOG;
DROP TABLE IF EXISTS ACT_APP_DATABASECHANGELOGLOCK;
DROP TABLE IF EXISTS ACT_APP_APPDEF;
DROP TABLE IF EXISTS ACT_APP_DEPLOYMENT;
DROP TABLE IF EXISTS ACT_APP_DEPLOYMENT_RESOURCE;
DROP TABLE IF EXISTS ACT_CMMN_CASEDEF;
DROP TABLE IF EXISTS ACT_CMMN_DATABASECHANGELOG;
DROP TABLE IF EXISTS ACT_CMMN_DATABASECHANGELOGLOCK;
DROP TABLE IF EXISTS ACT_CMMN_DEPLOYMENT;
DROP TABLE IF EXISTS ACT_CMMN_DEPLOYMENT_RESOURCE;
DROP TABLE IF EXISTS ACT_CMMN_HI_CASE_INST;
DROP TABLE IF EXISTS ACT_CMMN_HI_MIL_INST;
DROP TABLE IF EXISTS ACT_CMMN_HI_PLAN_ITEM_INST;
DROP TABLE IF EXISTS ACT_CMMN_RU_CASE_INST;
DROP TABLE IF EXISTS ACT_CMMN_RU_MIL_INST;
DROP TABLE IF EXISTS ACT_CMMN_RU_PLAN_ITEM_INST;
DROP TABLE IF EXISTS ACT_CMMN_RU_SENTRY_PART_INST;
DROP TABLE IF EXISTS ACT_DMN_DATABASECHANGELOG;
DROP TABLE IF EXISTS ACT_DMN_DATABASECHANGELOGLOCK;
DROP TABLE IF EXISTS ACT_DMN_DECISION;
DROP TABLE IF EXISTS ACT_DMN_DECISION_TABLE;
DROP TABLE IF EXISTS ACT_DMN_DEPLOYMENT;
DROP TABLE IF EXISTS ACT_DMN_DEPLOYMENT_RESOURCE;
DROP TABLE IF EXISTS ACT_DMN_HI_DECISION_EXECUTION;
DROP TABLE IF EXISTS ACT_EVT_LOG;
DROP TABLE IF EXISTS ACT_FO_DATABASECHANGELOG;
DROP TABLE IF EXISTS ACT_FO_DATABASECHANGELOGLOCK;
DROP TABLE IF EXISTS ACT_FO_FORM_DEFINITION;
DROP TABLE IF EXISTS ACT_FO_FORM_DEPLOYMENT;
DROP TABLE IF EXISTS ACT_FO_FORM_INSTANCE;
DROP TABLE IF EXISTS ACT_FO_FORM_RESOURCE;
DROP TABLE IF EXISTS ACT_GE_BYTEARRAY;
DROP TABLE IF EXISTS ACT_GE_PROPERTY;
DROP TABLE IF EXISTS ACT_HI_ACTINST;
DROP TABLE IF EXISTS ACT_HI_ATTACHMENT;
DROP TABLE IF EXISTS ACT_HI_COMMENT;
DROP TABLE IF EXISTS ACT_HI_DETAIL;
DROP TABLE IF EXISTS ACT_HI_IDENTITYLINK;
DROP TABLE IF EXISTS ACT_HI_PROCINST;
DROP TABLE IF EXISTS ACT_HI_TASKINST;
DROP TABLE IF EXISTS ACT_HI_VARINST;
DROP TABLE IF EXISTS ACT_ID_BYTEARRAY;
DROP TABLE IF EXISTS ACT_ID_GROUP;
DROP TABLE IF EXISTS ACT_ID_INFO;
DROP TABLE IF EXISTS ACT_ID_MEMBERSHIP;
DROP TABLE IF EXISTS ACT_ID_PRIV;
DROP TABLE IF EXISTS ACT_ID_PRIV_MAPPING;
DROP TABLE IF EXISTS ACT_ID_PROPERTY;
DROP TABLE IF EXISTS ACT_ID_TOKEN;
DROP TABLE IF EXISTS ACT_ID_USER;
DROP TABLE IF EXISTS ACT_PROCDEF_INFO;
DROP TABLE IF EXISTS ACT_RE_DEPLOYMENT;
DROP TABLE IF EXISTS ACT_RE_MODEL;
DROP TABLE IF EXISTS ACT_RE_PROCDEF;
DROP TABLE IF EXISTS ACT_RU_ACTINST;
DROP TABLE IF EXISTS ACT_RU_DEADLETTER_JOB;
DROP TABLE IF EXISTS ACT_RU_EVENT_SUBSCR;
DROP TABLE IF EXISTS ACT_RU_EXECUTION;
DROP TABLE IF EXISTS ACT_RU_EXTERNAL_JOB;
DROP TABLE IF EXISTS ACT_RU_HISTORY_JOB;
DROP TABLE IF EXISTS ACT_RU_IDENTITYLINK;
DROP TABLE IF EXISTS ACT_RU_JOB;
DROP TABLE IF EXISTS ACT_RU_SUSPENDED_JOB;
DROP TABLE IF EXISTS ACT_RU_TASK;
DROP TABLE IF EXISTS ACT_RU_TIMER_JOB;
DROP TABLE IF EXISTS ACT_RU_VARIABLE;
DROP TABLE IF EXISTS FLW_CHANNEL_DEFINITION;
DROP TABLE IF EXISTS FLW_EVENT_DATABASECHANGELOG;
DROP TABLE IF EXISTS FLW_EVENT_DATABASECHANGELOGLOCK;
DROP TABLE IF EXISTS FLW_EVENT_DEFINITION;
DROP TABLE IF EXISTS FLW_EVENT_DEPLOYMENT;
DROP TABLE IF EXISTS FLW_EVENT_RESOURCE;
DROP TABLE IF EXISTS FLW_RU_BATCH;
DROP TABLE IF EXISTS FLW_RU_BATCH_PART;
*/

-- 方案2: 更新版本号（如果表已存在但版本不匹配）
-- 将版本号更新为Flowable 6.8.1期望的版本

-- 检查当前版本
SELECT * FROM ACT_GE_PROPERTY WHERE NAME_ = 'schema.version';
SELECT * FROM ACT_ID_PROPERTY WHERE NAME_ = 'schema.version';

-- 更新版本号为6.8.1.0（如果表存在且版本不匹配）
-- UPDATE ACT_GE_PROPERTY SET VALUE_ = '6.8.1.0' WHERE NAME_ = 'schema.version';
-- UPDATE ACT_ID_PROPERTY SET VALUE_ = '6.8.1.0' WHERE NAME_ = 'schema.version';

-- 方案3: 检查是否有其他数据库也有Flowable表导致冲突
-- 如果同一个MySQL实例中有多个数据库都有Flowable表，可能会导致版本检查混乱
-- 确保只在一个数据库中使用Flowable，或者在application.yml中明确指定数据库名

-- 查看所有数据库中的Flowable表
-- SELECT TABLE_SCHEMA, TABLE_NAME 
-- FROM information_schema.TABLES 
-- WHERE TABLE_NAME LIKE 'ACT_%' OR TABLE_NAME LIKE 'FLW_%';

-- =============================================
-- 建议：
-- 1. 开发环境：直接删除所有表，让Flowable自动创建（方案1）
-- 2. 生产环境：备份数据后，更新版本号（方案2）
-- 3. 如果还有问题，检查配置中的database-schema-update设置
-- =============================================
